[workspace]
members = [
    "vd-controller",
    "vd-driver",
    "x264-sys",
    "x264",
    "mfx-dispatch-sys",
    "mfx-dispatch",
    "opus-sys",
    "opus",
    "windows-mft-encode",
    "nvcodec-sys",
    "nvcodec",
]
