[workspace]
resolver = "2"
members = [
    "vd-controller",
    "vd-driver",
    "opus-sys",
    "opus",
    "windows-mft-encode",
    "ffmpeg-sys",
    "ffmpeg-simple",
    "ffmpeg-test",
]

[workspace.dependencies]
bindgen = "0.70.0"
