// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class Audio {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Audio {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAudio(bb:flatbuffers.ByteBuffer, obj?:Audio):Audio {
  return (obj || new Audio()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAudio(bb:flatbuffers.ByteBuffer, obj?:Audio):Audio {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Audio()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

timestamp():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startAudio(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addTimestamp(builder:flatbuffers.Builder, timestamp:bigint) {
  builder.addFieldInt64(0, timestamp, BigInt('0'));
}

static endAudio(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createAudio(builder:flatbuffers.Builder, timestamp:bigint):flatbuffers.Offset {
  Audio.startAudio(builder);
  Audio.addTimestamp(builder, timestamp);
  return Audio.endAudio(builder);
}
}
