// automatically generated by the FlatBuffers compiler, do not modify

import { Audio } from '../../../moe/reimu/virtualdisplay/audio.js';
import { Configure } from '../../../moe/reimu/virtualdisplay/configure.js';
import { CursorImage } from '../../../moe/reimu/virtualdisplay/cursor-image.js';
import { CursorPosition } from '../../../moe/reimu/virtualdisplay/cursor-position.js';
import { Timestamp } from '../../../moe/reimu/virtualdisplay/timestamp.js';
import { Video } from '../../../moe/reimu/virtualdisplay/video.js';


export enum Command {
  NONE = 0,
  Video = 1,
  Audio = 2,
  Timestamp = 3,
  Configure = 4,
  CursorPosition = 5,
  CursorImage = 6
}

export function unionToCommand(
  type: Command,
  accessor: (obj:Audio|Configure|CursorImage|CursorPosition|Timestamp|Video) => Audio|Configure|CursorImage|CursorPosition|Timestamp|Video|null
): Audio|Configure|CursorImage|CursorPosition|Timestamp|Video|null {
  switch(Command[type]) {
    case 'NONE': return null; 
    case 'Video': return accessor(new Video())! as Video;
    case 'Audio': return accessor(new Audio())! as Audio;
    case 'Timestamp': return accessor(new Timestamp())! as Timestamp;
    case 'Configure': return accessor(new Configure())! as Configure;
    case 'CursorPosition': return accessor(new CursorPosition())! as CursorPosition;
    case 'CursorImage': return accessor(new CursorImage())! as CursorImage;
    default: return null;
  }
}

export function unionListToCommand(
  type: Command, 
  accessor: (index: number, obj:Audio|Configure|CursorImage|CursorPosition|Timestamp|Video) => Audio|Configure|CursorImage|CursorPosition|Timestamp|Video|null, 
  index: number
): Audio|Configure|CursorImage|CursorPosition|Timestamp|Video|null {
  switch(Command[type]) {
    case 'NONE': return null; 
    case 'Video': return accessor(index, new Video())! as Video;
    case 'Audio': return accessor(index, new Audio())! as Audio;
    case 'Timestamp': return accessor(index, new Timestamp())! as Timestamp;
    case 'Configure': return accessor(index, new Configure())! as Configure;
    case 'CursorPosition': return accessor(index, new CursorPosition())! as CursorPosition;
    case 'CursorImage': return accessor(index, new CursorImage())! as CursorImage;
    default: return null;
  }
}
