// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class CursorImage {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CursorImage {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCursorImage(bb:flatbuffers.ByteBuffer, obj?:CursorImage):CursorImage {
  return (obj || new CursorImage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCursorImage(bb:flatbuffers.ByteBuffer, obj?:CursorImage):CursorImage {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CursorImage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

crc32():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

png(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

pngLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

pngArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startCursorImage(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addCrc32(builder:flatbuffers.Builder, crc32:number) {
  builder.addFieldInt32(0, crc32, 0);
}

static addPng(builder:flatbuffers.Builder, pngOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, pngOffset, 0);
}

static createPngVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startPngVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endCursorImage(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCursorImage(builder:flatbuffers.Builder, crc32:number, pngOffset:flatbuffers.Offset):flatbuffers.Offset {
  CursorImage.startCursorImage(builder);
  CursorImage.addCrc32(builder, crc32);
  CursorImage.addPng(builder, pngOffset);
  return CursorImage.endCursorImage(builder);
}
}
