// automatically generated by the FlatBuffers compiler, do not modify

package moe.reimu.virtualdisplay

@Suppress("unused")
@kotlin.ExperimentalUnsignedTypes
class Command private constructor() {
    companion object {
        const val NONE: UByte = 0u
        const val Video: UByte = 1u
        const val Audio: UByte = 2u
        const val Timestamp: UByte = 3u
        const val Configure: UByte = 4u
        const val CursorPosition: UByte = 5u
        const val CursorImage: UByte = 6u
    }
}
